### ISSUE TITLE
isit dependence problem

### ISSUE THREAD

**Issue by patrickts** [toxinu/ubik#54]
I cannot install ubik on my centos 6.8 with pip
when i launch "pip install ubik" the required version of isit is not found (isit==0.3)

> No matching distribution found for isit==0.3 (from ubik)

i've then installed isit :

> [root@vagrant-centos64 ~]# pip install isit
> ...
> Successfully installed isit-0.3.5
> 

but next try is the same : 

> [root@vagrant-centos64 ~]# pip install ubik
> Collecting ubik
> /usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
>   SNIMissingWarning
> /usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
>   InsecurePlatformWarning
>   Downloading ubik-0.2.5.tar.gz (137kB)
>     100% |████████████████████████████████| 143kB 60kB/s
> Collecting progressbar==2.3 (from ubik)
>   Using cached progressbar-2.3.tar.gz
> Collecting requests==1.1.0 (from ubik)
>   Using cached requests-1.1.0.tar.gz
> Collecting docopt==0.5.0 (from ubik)
>   Using cached docopt-0.5.0.tar.gz
> Collecting isit==0.3 (from ubik)
>   Could not find a version that satisfies the requirement isit==0.3 (from ubik) (from versions: 0.3.4, 0.3.5)
> No matching distribution found for isit==0.3 (from ubik)

**Comment by toxinu** [comment]
I just pushed a fix. Can you try again please ?

**Comment by toxinu** [comment]
I recommend you to stick to pip version instead of old git branch.

`pip install ubik==0.2.6`
**instead of**
`pip install --upgrade git+https://github.com/toxinu/ubik.git@0.1`.

**Comment by patrickts** [comment]
yes installation of ubik==0.2.6 is ok

**Comment by patrickts** [comment]
thanks
